name: Zed clients polyglot SDK matrix

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '5 4 * * 2,5'
  workflow_dispatch:
  repository_dispatch:
    types: [clients-updated]

permissions:
  contents: read

jobs:
  sdk-clients:
    uses: zed-pkg-test/.github/.github/workflows/sdk-client-language-matrix.yml@59b6e9ae09988cd19db3c890f87df0ff8d8bbb69
    with:
      clients_repository: zed-pkg/zed-clients
      clients_ref: main
      clients_root: clients
      interfaces_repository: zed-pkg/zed-interfaces
      interfaces_ref: main
      interfaces_path: zed-interfaces
      interfaces_dependency: zed-pkg/zed-interfaces
      disabled_languages: kotlin,zig
    secrets:
      read_token: ${{ secrets.TEST_ORG_READ_TOKEN }}
