name: Zed clients polyglot SDK matrix

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '5 4 * * 2,5'
  workflow_dispatch:
  repository_dispatch:
    types: [clients-updated]

permissions:
  contents: read

jobs:
  sdk-clients:
    uses: zed-pkg-test/.github/.github/workflows/sdk-client-language-matrix.yml@293872964139a87228e89228f2107e19e40305e2
    with:
      clients_repository: zed-pkg/zed-clients
      clients_ref: main
      clients_root: clients
    secrets:
      read_token: ${{ secrets.TEST_ORG_READ_TOKEN }}
